ClassesAndObjects folder done
KasparsVanags/c-sharp-syllabus pull request #6
Opened 2022-08-01 14:46 UTC by KasparsVanags

2022-08-02 18:41 UTC, ausmoons requested changes

2022-08-02 18:41 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise1/Program.cs
> +        static double GetInput()
Tev vajag double vai int? Tu pēc tam convertē uz int

2022-08-02 18:41 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise12/Program.cs
> +            void ListTests(IStudent student)
Metode metode?

2022-08-02 18:41 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise13/Smoothie.cs
> +                {"Strawberries", (decimal)1.5},
Tab nav ok

2022-08-02 18:41 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise13/Smoothie.cs
> +        public string GetCost()
Starp metodēm vajag tukšu rindu

2022-08-02 18:41 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise3/Odometer.cs
> +        private bool CarHasFuel()
HasCarFuel

2022-08-02 18:41 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise6/Dog.cs
> +            if (Mother == dog.Mother && Mother != null)
Return uzreiz

2022-08-02 18:41 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise7/Program.cs
> +            string FormatCurrency(decimal currency)
Metode metode atkal

2022-08-02 18:41 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/VideoStore/Video.cs
> +        private readonly List<double> _ratingList = new List<double>();
Pēc propertijiem tukšu rindu

2022-08-02 19:04 UTC, KasparsVanags commented on csharp-basics/exercises/ClassesAndObjects/Exercise1/Program.cs
> +        static double GetInput()
Cenai double, citur int.
Laikam pārstaisīšu return uz int un cenu atsevišķi paņemšu. Der tāds variants?

2022-08-03 17:25 UTC, ausmoons approved these changes

2022-08-03 17:25 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise6/Dog.cs
> +            return (Mother == dog.Mother && Mother != null);
Iekavas ir liekas

2022-08-03 17:42 UTC, merged